### PR TITLE
hot fix - at end of jenkins pipeline, return control to machine

### PR DESCRIPTION
**Pull request by guyrodoy1**

### CODE REVIEW

**Comment by guyrodoy1** [comment]
test orb_slam_build_pr

**Comment by guyrodoy1** [comment]
test orb_slam_build_pr

**Comment by guyrod** [comment]
test orb_slam_build_pr

**Comment by guyrodoy1** [comment]
test orb_slam_build_pr

**Comment by guyrodoy1** [comment]
test orb_slam_build_pr

**Comment by guyrod** [comment]
test orb_slam_build_pr

**Comment by guyrodoy1** [comment]
test orb_slam_build_pr

**Comment by guyrodoy1** [comment]
test orb_slam_build_pr

**Review by ron-lbb — APPROVED** [review]

**Pull request merged**
